version: '3'
services:
    onyx:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '5173:5173'
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - /app/node_modules
            - .:/app
